name: Snapshot

on:
  workflow_dispatch:

jobs:
  release:

    name: Snapshot to Maven Central
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish snapshot to Maven Central
        run: |
          mvn -B deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
